Traceback (most recent call last):
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from myst_nb import glue

# Matplotlib settings
plt.style.use('default')
plt.rcParams['font.size'] = 10

# Sample data
t_sec = pd.DataFrame([1.41, 1.35, 1.45, 1.43, 1.44, 1.43,
                      1.41, 1.32, 1.43, 1.40, 1.49, 1.40,
                      1.40, 1.42, 1.40, 1.38, 1.37, 1.36,
                      1.37, 1.32, 1.47, 1.40])
klasse = np.linspace(1.3, 1.5, 6)

# Calculate the histogram using np.histogram
hist_values, bin_edges = np.histogram(t_sec, bins=klasse)

ax.set_ylabel('Absolute HÃ¤ufigkeit f')
ax.set_xlabel('Klassenverteilung der Zeit (s)')

# Use Myst-NB to display the figure with a custom label
glue("boot_fig", fig, display=True)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 23[0m
[1;32m     20[0m [38;5;66;03m# Calculate the histogram using np.histogram[39;00m
[1;32m     21[0m hist_values, bin_edges [38;5;241m=[39m np[38;5;241m.[39mhistogram(t_sec, bins[38;5;241m=[39mklasse)
[0;32m---> 23[0m [43max[49m[38;5;241m.[39mset_ylabel([38;5;124m'[39m[38;5;124mAbsolute HÃ¤ufigkeit f[39m[38;5;124m'[39m)
[1;32m     24[0m ax[38;5;241m.[39mset_xlabel([38;5;124m'[39m[38;5;124mKlassenverteilung der Zeit (s)[39m[38;5;124m'[39m)
[1;32m     26[0m [38;5;66;03m# Use Myst-NB to display the figure with a custom label[39;00m

[0;31mNameError[0m: name 'ax' is not defined
NameError: name 'ax' is not defined

