Traceback (most recent call last):
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from scipy.fft import rfft, rfftfreq
from scipy.io.wavfile import read #import the required function from the module
import matplotlib.pyplot as plt
import numpy as np
# MatplotLib Settings:
plt.style.use('default') # Matplotlib Style wÃ¤hlen
plt.figure(figsize=(8,3)) # Plot-GrÃ¶ÃŸe
#plt.xkcd()
plt.rcParams['font.size'] = 10; # SchriftgrÃ¶ÃŸe

samplerate, data = read('CantinaBand3.wav')
duration = len(data)/samplerate
time = np.arange(0,duration,1/samplerate) #time vector

Fs = 22050.0;  # sampling rate
Ts = 1.0/Fs; # sampling interval
t = np.arange(0,0.02,Ts) # time vector
ff = 1000;   # frequency of the carrier
f_m = 100
maxN = int(Fs/2)
# Sinusschwingung
f = lambda freq, ampl, t:  ampl*np.sin(2*np.pi*freq*t)
y = f(ff,1.0,t)
y_nutz = f(f_m,1.0,t)

data_norm = data/np.max(data)
y_nutz_norm = y_nutz/np.max(y_nutz)
plt.subplot(1,2,1)
#plt.plot(time, data_norm, 'tab:blue')
plt.plot(t, y_nutz_norm, 'tab:blue')
plt.xlabel('Zeit (s)')
plt.ylabel('Amplitude')
plt.title('Nachricht')
#plt.xlim([0.0,0.3])
#plt.ylim([-0.4,0.4])

plt.subplot(1,2,2)
plt.plot(t, y, 'k')
plt.xlabel('Zeit (s)')
plt.ylabel('Amplitude')
plt.title('TrÃ¤gersignal')
#plt.xlim([0.0,0.3])

plt.tight_layout()
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[1], line 11[0m
[1;32m      8[0m [38;5;66;03m#plt.xkcd()[39;00m
[1;32m      9[0m plt[38;5;241m.[39mrcParams[[38;5;124m'[39m[38;5;124mfont.size[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;241m10[39m; [38;5;66;03m# SchriftgrÃ¶ÃŸe[39;00m
[0;32m---> 11[0m samplerate, data [38;5;241m=[39m [43mread[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mCantinaBand3.wav[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m     12[0m duration [38;5;241m=[39m [38;5;28mlen[39m(data)[38;5;241m/[39msamplerate
[1;32m     13[0m time [38;5;241m=[39m np[38;5;241m.[39marange([38;5;241m0[39m,duration,[38;5;241m1[39m[38;5;241m/[39msamplerate) [38;5;66;03m#time vector[39;00m

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/scipy/io/wavfile.py:647[0m, in [0;36mread[0;34m(filename, mmap)[0m
[1;32m    645[0m     mmap [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[1;32m    646[0m [38;5;28;01melse[39;00m:
[0;32m--> 647[0m     fid [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m    649[0m [38;5;28;01mtry[39;00m:
[1;32m    650[0m     file_size, is_big_endian [38;5;241m=[39m _read_riff_chunk(fid)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'CantinaBand3.wav'
FileNotFoundError: [Errno 2] No such file or directory: 'CantinaBand3.wav'

