Traceback (most recent call last):
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/KSIsleif/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# diesen Code durch Eingabe von <shift><ret> ausf√ºhren

P = 1e-6     # Beispiels eines Messwerts in W, hier 1 uW
P_ref = 1e-3 # Referenzwert = 1 mW
P_dB = 10 * np.log10(P/P_ref) # Achtung: in numpy ist "log" der nat√ºrlich Logarithmus ln
print('Leistung = %.e W = %.10f W' %(P, P))
print('Pegel in dB: ', P_dB, '(%.3f)' %(P_ref))# In diesem Code Block k√∂nnen Umrechnungen f√ºr verschiedene Messwerte ausprobiert werden:
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 5>[0;34m()[0m
[1;32m      3[0m P [38;5;241m=[39m [38;5;241m1e-6[39m     [38;5;66;03m# Beispiels eines Messwerts in W, hier 1 uW[39;00m
[1;32m      4[0m P_ref [38;5;241m=[39m [38;5;241m1e-3[39m [38;5;66;03m# Referenzwert = 1 mW[39;00m
[0;32m----> 5[0m P_dB [38;5;241m=[39m [38;5;241m10[39m [38;5;241m*[39m [43mnp[49m[38;5;241m.[39mlog10(P[38;5;241m/[39mP_ref) [38;5;66;03m# Achtung: in numpy ist "log" der nat√ºrlich Logarithmus ln[39;00m
[1;32m      6[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mLeistung = [39m[38;5;124m%[39m[38;5;124m.e W = [39m[38;5;132;01m%.10f[39;00m[38;5;124m W[39m[38;5;124m'[39m [38;5;241m%[39m(P, P))
[1;32m      7[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mPegel in dB: [39m[38;5;124m'[39m, P_dB, [38;5;124m'[39m[38;5;124m([39m[38;5;132;01m%.3f[39;00m[38;5;124m)[39m[38;5;124m'[39m [38;5;241m%[39m(P_ref))

[0;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

